# Generated by Django 6.0 on 2026-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakerequest',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
