# Generated by Django 6.0 on 2026-09-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_message',
            field=models.CharField(blank=True, help_text='Message to write on the cake', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='prep_time',
            field=models.CharField(blank=True, help_text="e.g. '24-48 hours notice'", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='serving_size',
            field=models.CharField(blank=True, help_text="e.g. 'Serves 8-10'", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='flavours',
            field=models.ManyToManyField(blank=True, to='store.flavour'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
