# Generated by Django 6.0 on 2026-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_flavour_cartitem_custom_message_product_prep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
