# Generated by Django 6.0 on 2026-09-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderitem_custom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='flavour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.flavour'),
        ),
    ]
