# Generated by Django 6.0 on 2026-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/thumbs/'),
        ),
    ]
